# Generated by Django 5.1
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExtractedMetadata",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("filename", models.CharField(max_length=255)),
                ("file_hash", models.CharField(max_length=64, unique=True)),
                ("title", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("creator", models.TextField(blank=True)),
                ("rights", models.TextField(blank=True)),
                ("keywords", models.TextField(blank=True)),
                ("all_metadata", models.TextField()),
                ("extracted_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ausgelesene_metadaten",
                "ordering": ["-extracted_at"],
            },
        ),
    ]

    def run(self, runner, **kwargs):
        super().run(runner, **kwargs)
        print("SELECT * FROM ausgelesene_metadaten;")
