# Generated by Django 5.2.17 on 2026-10-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("metadata_tool", "0002_storedimage_userpreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="storedimage",
            name="last_scale",
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
